Proje4/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view),
    path('category/', include("category.urls")),
    path('article/', include("article.urls")),
    path('users/', include("users.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from .views import article_view, CreateText_view, addComment_view

app_name = "article"

urlpatterns = [
    path('createText', CreateText_view, name='createText'),
    path('addComment', addComment_view, name='addComment'),
    path('<str:slug>', article_view, name='articleDetail'),
]

category/urls.py
from .views import index_view, category_view
from django.urls import path

app_name = "category"

urlpatterns = [
    path('', index_view, name="index"),
    path('<str:slug>', category_view)
]

users/urls.py
from django.conf.urls import url
from .views import signupView, activate, account_activation_sent, user_login, user_logout, user_edit_profile, user_change_password

urlpatterns = [
    url(r'^register/$', signupView, name='register'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate,
        name='activate'),
    url(r'^login/$', user_login, name='user_login'),
    url(r'^logout/$', user_logout, name='user_logout'),
    url(r'^user_edit_profile/$', user_edit_profile, name='user_edit_profile'),
    url(r'^change_password/$', user_change_password, name='change_password'),


]

templates/base.html
{% load static %}
<!-- STATIC FILES LOADED -->

<!DOCTYPE html>
<html lang="en">
    <head>
    <!-- TITLE CONTENT -->
        <title>
            {% block title %}
                WHERE AM I?
            {% endblock %}
        </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- FONTS -->
        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">

        <!-- CSS FILES -->
        <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/aos.css' %}">
        <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        {% include 'header.html' %}

        {% block section %}

            <!-- PAGE INDEX -->

        {% endblock %}

        <!-- SCRIPT FILES -->
        <script src="{% static 'js/jquery.min.js'%}"></script>
        <script src="{% static 'js/jquery-migrate-3.0.1.min.js'%}"></script>
        <script src="{% static 'js/popper.min.js'%}"></script>
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
        <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
        <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
        <script src="{% static 'js/jquery.stellar.min.js'%}"></script>
        <script src="{% static 'js/owl.carousel.min.js'%}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
        <script src="{% static 'js/aos.js'%}"></script>
        <script src="{% static 'js/jquery.animateNumber.min.js'%}"></script>
        <script src="{% static 'js/scrollax.min.js'%}"></script>
        <script src="{% static 'js/main.js'%}"></script>

    </body>
</html>

templates/categories.html
{% extends 'base.html' %}  <!-- BASE.HTML EXTENDED RIGHT HERE -->
{% load static %} <!-- STATIC FILES LOADED -->
{% block title%}WHERE AM I?{% endblock %} <!-- TITLE CONTENT -->
{% block section %}
<section class="ftco-section ftco-no-pt ftco-no-pb">
    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
	    	<div class="container">
	    		<div class="row d-flex">
	    			<div class="col-lg-8 px-md-5 py-5">
	    				<div class="row pt-md-4">
                            <!-- CATEGORIES TITLE -->
                            {% if category %}
                                <h1 style="margin-left: 200px">{{ category.title }}</h1>
                            {% endif %}
                            <!-- FOR LOOP FOR CATEGORIES -->
                            {% for category in categories %}
                            <div class="col-md-12">
									<div class="blog-entry ftco-animate d-md-flex">
                                        {% if article.image %}
                                            <a href="{% url 'article:articleDetail' article.slug %}" class="img img-2" style="background-image: url('{{ article.image.url }}');"></a>
                                        {% endif %}
                                        <div class="text text-2 pl-md-4">
				                            <h3 class="mb-2"><a href="{{ category.slug }}">{{ category.title }}</a></h3>
				                            <div class="meta-wrap">
												<p class="meta">
				              		                <span><i class="icon-calendar mr-2"></i>June 28, 2019</span>
				              		                <span><a href="{{ category.slug }}"><i class="icon-folder-o mr-2"></i>Travel</a></span>
				              		                <span><i class="icon-comment2 mr-2"></i>5 Comment</span>
				              	                </p>
			              	                </div>
				                            <p class="mb-4">Everything about {{ category.title }} is here.</p>
				                            <p><a href="{{ category.slug }}" class="btn-custom">Read More <span class="ion-ios-arrow-forward"></span></a></p>
				                        </div>
									</div>
                            </div>
                            {% endfor %}
	    		        </div>
	    	        </div>
                    <!-- PAGINATOR -->
                    {% if articles.has_previous %}
                        <a href="?page={{ articles.previous_page_number }}" class="load-more-btn"><b>PREVIOUS PAGE</b></a>
                    {% endif %}
                    {% if articles.has_next %}
                        <a href="?page={{ articles.next_page_number }}" class="load-more-btn"><b>NEXT PAGE</b></a>
                    {% endif %}
			    		</div>
            </div>
        </section>
    </div>
{% endblock %}
</section>

templates/form_template.html
{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
            <br>
            <b>{{ field.errors }}</b>
        {% endif %}
    {% if field.help_text %}
        {{ field.help_text|safe }}
    {% endif %}
        <br>
    </div>
{% endfor %}

templates/header.html
{% load static %} <!-- STATIC FILES LOADED -->
<body>
    <div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"></a>
		<aside id="colorlib-aside" role="complementary" class="js-fullheight"
               style="background-color: white;">
            <div class="sidebar-box pt-md-4">
                {% if request.user.is_authenticated %}
                    <form action="#" class="search-form" method="get">
	                    <div class="form-group">
                            <span class="icon icon-search"></span>
	                        <input name="query" value="{{ request.GET.query }}" type="text"
                                   class="form-control" placeholder="Type a keyword and hit enter">
	                    </div>
	                </form>
                {% endif %}
            </div>
            <ul> <!-- USER AUTHENTICATION REQUEST -->
                {% if request.user.is_authenticated %}
                    <a href="{% url 'user_edit_profile' %}" style="color:black"><i class="icon-account_box"></i> {{ request.user.get_full_name }}</a><br>
                    <a href="{% url 'user_edit_profile' %}" style="color:black" class="small"><i class="icon-edit"></i> Edit Your Profile</a><br><br>
                    <a href="{% url 'article:createText' %}" style="color:black"><i class="ion-md-create"></i> Create Article</a><br>
                {% else %}
                    <a href="{% url 'register' %}">SIGNUP</a><br>
                    <a href="{% url 'user_login' %}">LOGIN</a>
                {% endif %}
            </ul>
            <nav id="colorlib-main-menu" role="navigation">
				<ul>
					<li><a href="/"><i class="icon-home"></i> Home</a></li>
                    <li><a href="{% url 'category:index' %}"><i class="icon-folder"></i> Categories</a></li>
				</ul>
            </nav>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'user_logout' %}" style="color:black"><i class="ion-ios-log-out"></i> <b>LOGOUT</b></a>
                {% endif %}<br>
			<div class="colorlib-footer">
				<h1 id="colorlib-logo" class="mb-5"><a href="/" style="background-color: aqua;">Mahonny <span>Travel</span></a></h1>
				
			</div>
		</aside> <!-- END COLORLIB-ASIDE -->
	</div><!-- END COLORLIB-PAGE -->
</body>

templates/index.html
{% extends 'base.html' %}  <!-- BASE.HTML EXTENDED RIGHT HERE -->
{% load static %} <!-- STATIC FILES LOADED -->
{% block title%}WHERE AM I?{% endblock %} <!-- TITLE CONTENT -->
{% block section %}
			<section class="ftco-section ftco-no-pt ftco-no-pb">
	    		<div id="colorlib-main">
			        <section class="ftco-section ftco-no-pt ftco-no-pb">
	    	            <div class="container">
	    		            <div class="row d-flex">
	    			            <div class="col-lg-8 px-md-5 py-5">
	    				            <div class="row pt-md-4">
                                    {% for article in articles %}
                                        <div class="col-md-12">
									    <div class="blog-entry ftco-animate d-md-flex">
                                        <!-- ARTICLE IMAGE REQUEST -->
                                        {% if article.image %}
                                            <a href="{% url 'article:articleDetail' article.slug %}" class="img img-2" style="background-image: url('{{ article.image.url }}');"></a>
                                        {% endif %}
										    <div class="text text-2 pl-md-4">
                                                <!-- ARTICLE CONTENT REQUESTS -->
				                                <h3 class="mb-2"><a href="{% url 'article:articleDetail' article.slug %}">{{ article.title }}</a></h3>
				                                <div class="meta-wrap">
												    <p class="meta">
				              		                <span><i class="icon-calendar mr-2"></i>{{ article.releaseDate }}</span>
				              		                <span><a href="{% url 'article:articleDetail' article.slug %}"><i class="icon-folder-o mr-2"></i>{{ article.category }}</a></span>
                                                    <span><i class="ion-md-heart"></i> {{ article.like }} Like</span>
                                                    <span><i class="ion-md-eye"></i> {{ article.view }} Views</span>
				              	                    </p>
			              	                    </div>
				                                <p class="mb-4">{{ article.content | safe }}</p>
				                                <p><a href="{% url 'article:articleDetail' article.slug %}" class="btn-custom">Read More <span class="ion-ios-arrow-forward"></span></a></p>
                                                <br><hr>
				                            </div>
                                        </div></div>
                                    {% endfor %}
			    		            </div><!-- END-->
                                <!-- PAGINATOR -->
                                <div style="text-align: center">
                                    {% if articles.has_previous %}
                                    <a href="?page={{ articles.previous_page_number }}" class="load-more-btn"><b>PREVIOUS PAGE</b></a>
                                    {% endif %}|
                                    {% if articles.has_next %}
                                    <a href="?page={{ articles.next_page_number }}" class="load-more-btn"><b>NEXT PAGE</b></a>
                                    {% endif %}
                                </div>
			    	</div></div></div></section></div></section>
{% endblock %}